"""Foundation Disclosure — explicit statement of weakest assumptions.

Every council run should produce a foundation disclosure that makes the
foundations of the consensus visible so they can be inspected and challenged.
This is a critical trust mechanism: making the weakest assumptions explicit
rather than implicit.

Disclosure Components
=====================

1. **Weakest Assumptions** (1-3) — The assumptions most likely to break
   the conclusion if proven false.
2. **Invalidation Conditions** (1-2) — Conditions under which the
   consensus conclusion would no longer hold.
3. **Key Vulnerability** (1) — The most significant vulnerability in the
   deliberation process itself.

Analysis Signals
================

The disclosure is generated by analyzing:

- **Agent agreement level** — High agreement (all agents aligned) may indicate
  groupthink rather than genuine consensus.
- **Challenge severity** — How strong was the adversarial challenge? Weak
  challenges leave the consensus untested.
- **Evidence gaps** — What topics were mentioned without supporting evidence?
- **Missing perspectives** — Were there agent roles missing that would have
  been relevant (e.g., no technical expert for a tech decision)?

Architecture Diagram
====================

    CouncilReport ─────────────────────────────────────────────────┐
    │                                                              │
    ├─ posts[]          ──> agreement level, challenge severity,   │
    │                         evidence gaps, missing perspectives  │
    ├─ final_state     ──> LOCKED (normal) / other (attention)   │
    └─ agent_contributions ──> coverage of required perspectives │
                                                                 │
    ┌────────────────────────────────────────────────────────────┘
    │
    ▼
    FoundationDisclosure.generate_disclosure(report)
    │
    ├─ Analyze agreement level (confidence spread)
    ├─ Analyze challenge severity (contrarian body length, keywords)
    ├─ Identify evidence gaps (topics without evidence keywords)
    ├─ Detect missing perspectives (agent role coverage)
    │
    ▼
    FoundationDisclosureResult
    ├─ weakest_assumptions: list[str]  (1-3)
    ├─ invalidation_conditions: list[str]  (1-2)
    ├─ key_vulnerability: str  (1)
    ├─ agreement_level: str  ("high" / "moderate" / "low")
    ├─ challenge_severity: str  ("strong" / "moderate" / "weak" / "none")
    ├─ evidence_gaps: list[str]
    └─ missing_perspectives: list[str]
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from cme.spacebase.council import CouncilReport


@dataclass
class FoundationDisclosureResult:
    """Output of the foundation disclosure analysis.

    Attributes:
        weakest_assumptions: 1-3 weakest assumptions underlying the consensus.
        invalidation_conditions: 1-2 conditions that would invalidate the conclusion.
        key_vulnerability: The single most significant deliberation vulnerability.
        agreement_level: How aligned the agents were ("high", "moderate", "low").
        challenge_severity: How strong the adversarial challenge was.
        evidence_gaps: Topics mentioned without supporting evidence.
        missing_perspectives: Agent roles that should have been involved but weren't.
        council_id: The council that produced this disclosure.
        trace_id: Trace ID of the council run.
    """

    weakest_assumptions: list[str] = field(default_factory=list)
    invalidation_conditions: list[str] = field(default_factory=list)
    key_vulnerability: str = ""
    agreement_level: str = "unknown"
    challenge_severity: str = "unknown"
    evidence_gaps: list[str] = field(default_factory=list)
    missing_perspectives: list[str] = field(default_factory=list)
    council_id: str = ""
    trace_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a plain dict."""
        return {
            "weakest_assumptions": self.weakest_assumptions,
            "invalidation_conditions": self.invalidation_conditions,
            "key_vulnerability": self.key_vulnerability,
            "agreement_level": self.agreement_level,
            "challenge_severity": self.challenge_severity,
            "evidence_gaps": self.evidence_gaps,
            "missing_perspectives": self.missing_perspectives,
            "council_id": self.council_id,
            "trace_id": self.trace_id,
        }


class FoundationDisclosure:
    """Foundation disclosure — explicit statement of weakest assumptions.

    Every council run should produce a foundation disclosure:
    - 1-3 weakest assumptions underlying the consensus
    - 1-2 invalidation conditions that would break the conclusion
    - 1 key vulnerability in the deliberation process

    This is a critical trust mechanism: making the foundations of the
    consensus visible so they can be inspected and challenged.

    Usage::

        disclosure = FoundationDisclosure()
        result = disclosure.generate_disclosure(report)

        for assumption in result.weakest_assumptions:
            print(f"Weak assumption: {assumption}")

        for condition in result.invalidation_conditions:
            print(f"Invalidation: {condition}")

        print(f"Key vulnerability: {result.key_vulnerability}")
    """

    # Keywords indicating confidence/agreement
    AGREEMENT_KEYWORDS: set[str] = {
        "agree", "concur", "consensus", "aligned", "consistent",
        "confirmed", "validated", "supported", "endorsed",
        "recommend", "proceed", "pass", "approve",
    }

    # Keywords indicating challenge/severity
    CHALLENGE_KEYWORDS: set[str] = {
        "challenge", "concern", "risk", "vulnerability", "failure",
        "issue", "problem", "gap", "weakness", "threat",
        "danger", "warning", "critical", "blocker",
    }

    # Keywords indicating evidence
    EVIDENCE_KEYWORDS: set[str] = {
        "data", "evidence", "study", "research", "statistic",
        "benchmark", "metric", "result", "finding", "analysis",
        "source", "reference", "verified", "measured",
    }

    # Expected agent roles for comprehensive coverage
    EXPECTED_AGENT_ROLES: set[str] = {
        "analyst", "financial-analyst", "strategic-analyst",
        "contrarian", "validator", "compliance-validator",
        "technical-analyst", "legal-analyst", "risk-analyst",
        "domain-expert",
    }

    def generate_disclosure(
        self, report: CouncilReport,
    ) -> FoundationDisclosureResult:
        """Generate a foundation disclosure from a council report.

        Analyzes the council report to identify weakest assumptions,
        invalidation conditions, and key vulnerabilities.

        Args:
            report: A completed CouncilReport from a council run.

        Returns:
            A FoundationDisclosureResult with all disclosure components.
        """
        result = FoundationDisclosureResult(
            council_id=report.root_intent_id,
            trace_id=report.trace_id,
        )

        # Analyze each dimension
        result.agreement_level = self._analyze_agreement_level(report)
        result.challenge_severity = self._analyze_challenge_severity(report)
        result.evidence_gaps = self._identify_evidence_gaps(report)
        result.missing_perspectives = self._detect_missing_perspectives(report)

        # Generate weakest assumptions
        result.weakest_assumptions = self._derive_weakest_assumptions(
            report, result
        )

        # Generate invalidation conditions
        result.invalidation_conditions = self._derive_invalidation_conditions(
            report, result
        )

        # Generate key vulnerability
        result.key_vulnerability = self._derive_key_vulnerability(report, result)

        return result

    def assess_assumption_risk(self, assumption: str) -> dict[str, Any]:
        """Assess the risk level of a single assumption.

        Args:
            assumption: The assumption text to assess.

        Returns:
            A dict with risk assessment fields.
        """
        assumption_lower = assumption.lower()

        # Heuristic risk factors
        risk_factors: dict[str, Any] = {
            "assumption": assumption,
            "risk_level": "low",
            "factors": [],
        }

        # Strong claims (high risk if wrong)
        strong_claim_patterns = [
            r"\bwill\b", r"\bdefinitely\b", r"\bcertainly\b",
            r"\bguaranteed\b", r"\bno doubt\b", r"\bclearly\b",
        ]
        for pattern in strong_claim_patterns:
            if re.search(pattern, assumption_lower):
                risk_factors["risk_level"] = "high"
                risk_factors["factors"].append("Contains strong certainty language")

        # Quantitative claims without "if" hedging
        if re.search(r"\$[\d,]+|\d+%", assumption):
            if not re.search(r"\bif\b|\bassuming\b|\bdepending\b", assumption_lower):
                risk_factors["risk_level"] = "high"
                risk_factors["factors"].append("Quantitative claim without hedging")

        # Implicit temporal assumption
        temporal_patterns = [
            r"\bwill\s+(?:be|become|remain|stay)\b",
            r"\bin\s+(?:the\s+)?(?:future|next|coming)\b",
        ]
        for pattern in temporal_patterns:
            if re.search(pattern, assumption_lower):
                if risk_factors["risk_level"] == "low":
                    risk_factors["risk_level"] = "medium"
                risk_factors["factors"].append("Contains implicit temporal assumption")

        # Short assumptions tend to be less specific (higher risk)
        if len(assumption.split()) < 5:
            if risk_factors["risk_level"] == "low":
                risk_factors["risk_level"] = "medium"
            risk_factors["factors"].append("Very brief assumption — lacks specificity")

        if not risk_factors["factors"]:
            risk_factors["factors"].append("No specific risk factors identified")

        return risk_factors

    def format_for_council_report(
        self, disclosure: FoundationDisclosureResult,
    ) -> str:
        """Format a foundation disclosure as markdown for embedding in a council report.

        Args:
            disclosure: The FoundationDisclosureResult to format.

        Returns:
            A markdown-formatted string suitable for inclusion in council reports.
        """
        lines = [
            "## Foundation Disclosure",
            "",
            "> *This section documents the weakest assumptions, invalidation "
            "> conditions, and key vulnerabilities of this council's consensus.*",
            "",
        ]

        if disclosure.weakest_assumptions:
            lines.append("### Weakest Assumptions")
            for i, assumption in enumerate(disclosure.weakest_assumptions, 1):
                risk = self.assess_assumption_risk(assumption)
                risk_badge = {
                    "high": "🔴",
                    "medium": "🟡",
                    "low": "🟢",
                }.get(risk["risk_level"], "⚪")
                lines.append(f"{i}. {risk_badge} {assumption}")
                if risk["factors"]:
                    lines.append(f"   - Risk: {', '.join(risk['factors'])}")
            lines.append("")

        if disclosure.invalidation_conditions:
            lines.append("### Invalidation Conditions")
            lines.append(
                "*The consensus conclusion would be invalidated if:*"
            )
            for i, condition in enumerate(disclosure.invalidation_conditions, 1):
                lines.append(f"{i}. {condition}")
            lines.append("")

        if disclosure.key_vulnerability:
            lines.append("### Key Deliberation Vulnerability")
            lines.append(f"> {disclosure.key_vulnerability}")
            lines.append("")

        lines.append("### Meta-Analysis")
        lines.append(f"- **Agreement Level**: {disclosure.agreement_level}")
        lines.append(f"- **Challenge Severity**: {disclosure.challenge_severity}")
        if disclosure.evidence_gaps:
            lines.append(
                f"- **Evidence Gaps**: {', '.join(disclosure.evidence_gaps)}"
            )
        if disclosure.missing_perspectives:
            lines.append(
                f"- **Missing Perspectives**: "
                f"{', '.join(disclosure.missing_perspectives)}"
            )
        lines.append("")

        return "\n".join(lines)

    def _analyze_agreement_level(self, report: CouncilReport) -> str:
        """Analyze how aligned the agents' confidence scores are."""
        if not report.posts:
            return "unknown"

        confidences = [p.confidence for p in report.posts if p.confidence is not None]
        if not confidences:
            return "unknown"

        # Calculate spread
        avg_conf = sum(confidences) / len(confidences)
        spread = max(confidences) - min(confidences)

        if spread < 0.15:
            return "high"
        elif spread < 0.30:
            return "moderate"
        else:
            return "low"

    def _analyze_challenge_severity(self, report: CouncilReport) -> str:
        """Analyze how strong the adversarial challenge was."""
        contrarian_posts = [
            p for p in report.posts if p.agent == "contrarian"
        ]

        if not contrarian_posts:
            return "none"

        # Check the contrarian post body
        for post in contrarian_posts:
            body_lower = post.body.lower()
            challenge_count = sum(
                1 for kw in self.CHALLENGE_KEYWORDS if kw in body_lower
            )

            if challenge_count >= 5 and len(post.body) > 300:
                return "strong"
            elif challenge_count >= 2 and len(post.body) > 150:
                return "moderate"

        return "weak"

    def _identify_evidence_gaps(self, report: CouncilReport) -> list[str]:
        """Identify topics mentioned without supporting evidence."""
        gaps: list[str] = []

        # Extract "topic sentences" — capitalized phrases that look like topics
        all_body = " ".join(p.body for p in report.posts)
        topic_pattern = r"(?:^|\n)\s*(?:[-•]|\d+[.)])\s*(\w[\w\s]{5,50}?(?:[:.]\s))"

        for match in re.finditer(topic_pattern, all_body):
            topic = match.group(1).strip().rstrip(":. ")
            # Check if this topic has evidence keywords nearby
            start = max(0, match.start() - 100)
            end = min(len(all_body), match.end() + 300)
            context = all_body[start:end].lower()
            has_evidence = any(
                kw in context for kw in self.EVIDENCE_KEYWORDS
            )
            if not has_evidence:
                gaps.append(f"Claims about '{topic}' lack supporting evidence")

        # Deduplicate
        seen: set[str] = set()
        unique_gaps: list[str] = []
        for gap in gaps:
            if gap not in seen:
                seen.add(gap)
                unique_gaps.append(gap)

        return unique_gaps[:5]  # Cap at 5 gaps

    def _detect_missing_perspectives(self, report: CouncilReport) -> list[str]:
        """Detect agent roles that should have been involved but weren't."""
        actual_agents = set(report.agent_contributions.keys())
        missing: list[str] = []

        # Check for finance content without financial analyst
        all_body = " ".join(p.body.lower() for p in report.posts)
        finance_terms = {"budget", "investment", "capital", "roi", "revenue"}
        has_finance = any(term in all_body for term in finance_terms)
        if has_finance and "financial-analyst" not in actual_agents:
            missing.append("financial-analyst (finance content detected)")

        # Check for tech content without technical analyst
        tech_terms = {"code", "software", "api", "deploy", "architecture", "system"}
        has_tech = any(term in all_body for term in tech_terms)
        if has_tech and "technical-analyst" not in actual_agents:
            missing.append("technical-analyst (technical content detected)")

        # Check for legal/regulatory content
        legal_terms = {"regulatory", "compliance", "legal", "gdpr", "sox", "hipaa"}
        has_legal = any(term in all_body for term in legal_terms)
        if has_legal and "legal-analyst" not in actual_agents:
            missing.append("legal-analyst (regulatory/legal content detected)")

        return missing

    def _derive_weakest_assumptions(
        self,
        report: CouncilReport,
        partial: FoundationDisclosureResult,
    ) -> list[str]:
        """Derive the 1-3 weakest assumptions from the report analysis."""
        assumptions: list[str] = []

        # High agreement = possible groupthink
        if partial.agreement_level == "high":
            assumptions.append(
                "High agent agreement may indicate groupthink rather than "
                "genuine independent consensus — challenge severity should "
                "be scrutinized."
            )

        # Weak or missing challenge
        if partial.challenge_severity in ("weak", "none"):
            assumptions.append(
                "Adversarial challenge was insufficient to stress-test the "
                "consensus — conclusions may not withstand stronger objections."
            )

        # Evidence gaps
        if partial.evidence_gaps:
            assumptions.append(
                f"Claims lack supporting evidence in {len(partial.evidence_gaps)} "
                "areas — conclusions rely on unverified assertions."
            )

        # Missing perspectives
        if partial.missing_perspectives:
            assumptions.append(
                f"Missing perspectives: {', '.join(partial.missing_perspectives)} "
                "— consensus may be incomplete without these viewpoints."
            )

        # Default if no assumptions identified
        if not assumptions:
            assumptions.append(
                "All agents operated from the same information context — "
                "no independent verification of source data was performed."
            )

        return assumptions[:3]  # Cap at 3

    def _derive_invalidation_conditions(
        self,
        report: CouncilReport,
        partial: FoundationDisclosureResult,
    ) -> list[str]:
        """Derive 1-2 invalidation conditions from the analysis."""
        conditions: list[str] = []

        if partial.evidence_gaps:
            conditions.append(
                "If the unverified claims in evidence gaps prove false, "
                "the consensus conclusion does not hold."
            )

        if partial.missing_perspectives:
            conditions.append(
                "If the missing perspectives reveal critical information "
                "not available to current agents, the consensus is incomplete."
            )

        if not conditions:
            conditions.append(
                "If the underlying data or market conditions change "
                "significantly after this deliberation, conclusions may "
                "no longer be valid."
            )

        return conditions[:2]  # Cap at 2

    def _derive_key_vulnerability(
        self,
        report: CouncilReport,
        partial: FoundationDisclosureResult,
    ) -> str:
        """Derive the single most significant deliberation vulnerability."""
        vulnerabilities: list[str] = []

        if partial.challenge_severity in ("weak", "none"):
            vulnerabilities.append(
                "Insufficient adversarial stress-testing — the consensus was not "
                "adequately challenged before locking."
            )

        if partial.agreement_level == "high" and partial.challenge_severity != "strong":
            vulnerabilities.append(
                "High agreement with weak challenge suggests agents may have "
                "converged prematurely without sufficient critical evaluation."
            )

        if partial.evidence_gaps:
            vulnerabilities.append(
                f"{len(partial.evidence_gaps)} evidence gaps mean key claims "
                "are unsupported by verifiable data."
            )

        if partial.missing_perspectives:
            vulnerabilities.append(
                "Critical perspectives are absent from the deliberation, "
                "potentially creating blind spots in the consensus."
            )

        if not vulnerabilities:
            vulnerabilities.append(
                "Standard deliberation risk — conclusions reflect the best "
                "available analysis but carry inherent uncertainty."
            )

        return vulnerabilities[0]  # Return the top vulnerability
